Add post conditions for success and failure notifications

diff --git a/CD/jenkinsfile b/CD/jenkinsfile
--- a/CD/jenkinsfile
+++ b/CD/jenkinsfile
@@ -74,5 +74,15 @@ docker compose ps
 '''
 }
 }
-
+post{
+success{
+echo "CD pipeline completed suceessfully"
+}
+failure{
+echo "CD pipeline failed"
+}
+always{
+sh 'docker logout || true'
+}
+}
 }
